config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      post :auth, to: 'authentication#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, except: [:update, :edit] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  root 'users#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :comments_posts_counter

  private

  def comments_posts_counter
    post.increment!(:comments_counter)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApiController
  def index
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])

    return unless @post.comments.create(text: params[:comment][:text], author: @current_user)

    render json: { success: 'Comment created successfully' }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  before_action :set_user, only: [:create]
  before_action :set_post, only: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.author = current_user
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
      redirect_to user_post_path(current_user, @post)
    else
      flash[:alert] = 'Comment was not created.'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @user = @post.author
    @comment.destroy
    @post.comments_counter -= 1

    redirect_to user_post_path(@user, @post) if @post.save
  end

  def new
    @comment = Comment.new
    @current_user = current_user
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/views/comments/new.html.erb
<div class="bg-white rounded-lg p-4 mt-4">
    <%= form_with model: @comment, url: user_post_comments_path, data: { turbo: false } do |form| %>
      <div class="mb-4">
        <%= form.label :text, class: "block text-gray-700 font-medium mb-2" %>
        <%= form.text_area :text, class: "w-full h-32 border border-gray-400 p-2 rounded-lg" %>
      </div>
      <div class="text-center">
        <%= form.submit "Create Comment", class: "bg-gradient-to-tr from-[#3FBFED] via-[#35A5E5] to-[#319AE0] text-white py-2 px-4 rounded-lg hover:bg-blue-800 cursor-pointer" %>
      </div>
    <% end %>
</div>