config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      post :auth, to: 'authentication#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, except: [:update, :edit] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/views/users/index.html.erb
<div class="flex flex-col gap-4">
<% @users.reverse.each do |user| %>
    <div class="user">
        <%= link_to user_path(user) do %>
          <div class="flex flex-col p-4 items-center border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl bg-gradient-to-tr from-[#3FBFED] via-[#35A5E5] to-[#319AE0]">
              <% if user.photo? %>
                  <%= image_tag user.photo, class: "h-32 w-32 object-cover rounded-lg md:w-48 md:h-auto" %>
              <% else %>
                  <%= image_tag "https://avatars.dicebear.com/api/adventurer/4.svg", class: "h-10 w-10 object-cover rounded-lg md:w-48 md:h-auto" %>
              <% end %>
              <div class="flex flex-col justify-between p-4 leading-normal">
                  <h5 class="mb-2 text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
                  <%= user.name %>
                  </h5>
                  <p class="mb-3 text-xl font-normal text-gray-700">
                      Number of posts: <%= user.posts_counter %>
                  </p>
              </div>
          </div>
        <% end %>
    </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="flex flex-col">
<div class="p-6 rounded-lg shadow-md bg-gradient-to-tr from-[#3FBFED] via-[#35A5E5] to-[#319AE0]">
  <div class="flex items-center mb-6">
    <% if @user.photo? %>
        <%= image_tag @user.photo, class: "h-48 w-48 rounded-full object-cover" %>
    <% else %>
        <%= image_tag "https://avatars.dicebear.com/api/adventurer/4.svg", class: "h-48 w-48 rounded-full object-cover" %>
    <% end %>
    <div class="ml-4 flex flex-col gap-4">
      <h2 class="text-4xl font-bold text-gray-900"><%= @user.name %></h2>
      <p class="text-2xl text-gray-800"><%= @user.bio %></p>
      <p class="text-lg text-gray-800">Joined <%= time_ago_in_words(@user.created_at) %> ago</p>
      <p class="text-lg text-gray-800">Number of Posts: <%= @user.posts_counter %></p>
    </div>
  </div>
</div>
<h3 class="text-lg font-bold text-gray-800 mt-4">Recent Posts</h3>
<div class="flex flex-col">
<div class="p-6 rounded-lg shadow-md bg-[url('https://images.unsplash.com/photo-1601436155198-2ebfea8117b0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Ymx1ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60')]">
<% @user.posts.first(3).each do |post| %>
  <div class="mb-4 shadow-md p-4 rounded-md bg-clip-padding backdrop-filter backdrop-blur-xl bg-opacity-60 border border-gray-200">
    <a href="<%= user_post_path(@user, post) %>" class="text-xl font-bold text-blue-600 hover:underline">
      <%= post.title %>
    </a>
    <p class="text-black text-xl dark:text-white my-2">
      <%= post.text %>
    </p>
    <p class="text-gray-600 dark:text-white">
      <%= time_ago_in_words(post.created_at) %> ago
    </p>
    <div class="flex justify-end gap-5 items-end mt-2 dark:text-white">
    <p>Comments:<%= post.comments_counter %></p>
    <p>Likes: <%= post.likes_counter %></p>
    </div>
  </div>
<% end %>
</div>
</div>
  <%= link_to user_posts_path(@user) do %>
    <div class="flex justify-center my-4">
      <button class="bg-gradient-to-tr from-[#3FBFED] via-[#35A5E5] to-[#319AE0] text-white px-4 py-2 rounded font-medium hover:bg-blue-600">See All Posts</button>
    </div>
    <% end %>
</div>