config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      post :auth, to: 'authentication#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, except: [:update, :edit] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  root 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  def index
    @user = User.find(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes([:comments])
  end

  def new
    @post = Post.new
    @current_user = current_user
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = Comment.includes([:author]).where(post_id: params[:id]).order(created_at: :desc).limit(5)
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to user_posts_path(current_user)
    else
      flash[:alert] = 'Post creation failed'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = @post.author
    delete_post_and_its_related_objects(@post)
    @user.posts_counter -= 1
    flash[:notice] = 'Post deleted successfully'

    redirect_to user_posts_path(@user) if @user.save
  end

  private

  def delete_post_and_its_related_objects(post)
    if post.comments_counter.positive? || post.likes_counter.positive?
      post.comments.each(&:destroy) if post.comments_counter.positive?
      post.likes.each(&:destroy) if post.likes_counter.positive?
    end
    post.destroy
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class="flex flex-col">
<div class="p-6 rounded-lg shadow-md bg-gradient-to-tr from-[#3FBFED] via-[#35A5E5] to-[#319AE0]">
  <div class="flex items-center mb-6">
    <% if @user.photo? %>
        <%= image_tag @user.photo, class: "h-48 w-48 rounded-full object-cover" %>
    <% else %>
        <%= image_tag "https://avatars.dicebear.com/api/adventurer/4.svg", class: "h-48 w-48 rounded-full object-cover" %>
    <% end %>
    <div class="ml-4 flex flex-col gap-4">
      <h2 class="text-4xl text-gray-900 font-bold"><%= @user.name %></h2>
      <p class="text-2xl text-gray-800"><%= @user.bio %></p>
      <p class="text-lg text-gray-800">Joined <%= time_ago_in_words(@user.created_at) %> ago</p>
      <p class="text-lg text-gray-800">Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
</div>
<h3 class="text-lg font-bold text-gray-800 mt-4">Posts</h3>
<div class="flex flex-col">
<div class="bg-white p-6 rounded-lg shadow-md bg-[url('https://images.unsplash.com/photo-1601436155198-2ebfea8117b0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Ymx1ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60')]">
<% @user.posts.includes([:comments]).each do |post| %>
  <div class="mb-4 shadow-md p-4 rounded-md bg-clip-padding backdrop-filter backdrop-blur-xl bg-opacity-60 border border-gray-200">
    <a href="<%= user_post_path(@user, post) %>" class="text-lg font-medium text-blue-600 hover:underline">
      <%= post.title %>
    </a>
    <p class="text-gray-800">
      <%= post.text %>
    </p>
    <p class="text-gray-600">
      <%= time_ago_in_words(post.created_at) %> ago
    </p>
    <div class="flex justify-end gap-5 items-end mt-2">
    <p>Comments:<%= post.comments_counter %></p>
    <p>Likes: <%= post.likes_counter %></p>
    </div>
      <% if post.comments.empty? %>
  <p class="my-8">There are no comments for this post.</p>
<% else %>
  <% post.comments.includes([:author]).each do |comment| %>
    <div class="bg-white rounded-lg p-4 shadow-md">
      <p class="text-gray-700 font-medium"><%= comment.text %></p>
      <p class="text-gray-500 font-medium">by <%= comment.author.name %></p>
      <hr class="my-4">
    </div>
  <% end %>
<% end %> 
<hr class="my-4">
  </div>
<% end %>
</div>
</div>
</div>

app/views/posts/new.html.erb
<div class="bg-white p-6 rounded-lg">
  <%= form_with model: @post, url: user_posts_path, data: { turbo: false } do |form| %>
    <div class="mb-4">
      <%= form.label :title, class: "block text-gray-700 font-medium mb-2" %>
      <%= form.text_field :title, class: "w-full border border-gray-400 p-2 rounded-lg" %>
    </div>
    <div class="mb-4">
      <%= form.label :text, class: "block text-gray-700 font-medium mb-2" %>
      <%= form.text_area :text, class: "w-full h-32 border border-gray-400 p-2 rounded-lg" %>
    </div>
    <div class="text-center">
      <%= form.submit "Create Post", class: "bg-indigo-500 text-white py-2 px-4 rounded-lg hover:bg-indigo-600" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="p-6 rounded-lg shadow-md bg-gradient-to-tr from-[#3FBFED] via-[#35A5E5] to-[#319AE0]">
  <div class="p-4">
    <h2 class="text-xl font-bold text-gray-900">
        <%= @post.title %>
    </h2>
    <p class="text-base text-gray-800 my-4">
      <%= @post.text %>
    </p>
    <p class="text-sm text-gray-600">
      <%= time_ago_in_words(@post.created_at) + " ago" %>
    </p>
  </div>
<%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes" do |form| %>  
  <button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded cursor-pointer">
    <svg class="fill-current h-4 w-4" viewBox="0 0 24 24">
      <path d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"/>
    </svg>
    <%= form.submit 'Like' %>
  </button>
<% end %>
  <div class="px-4 py-3 bg-gray-100 rounded-lg my-4">
    <p class="text-sm text-gray-600">
      <span class="text-gray-800">Author:</span> <%= @post.author.name %>
    </p>
    <p class="text-sm text-gray-600">
      <span class="text-gray-800">Likes:</span> <%= @post.likes_counter %>
    </p>
    <p class="text-sm text-gray-600">
      <span class="text-gray-800">Comments:</span> <%= @post.comments_counter %>
    </p>
  </div>
  <% if @comments.empty? %>
  <p class="my-4">There are no comments for this post.</p>
<% else %>
  <div class="rounded-lg shadow-md bg-white p-4 my-4">
  <% @comments.reverse.each do |comment| %>
    <div class="">
      <p class="text-gray-700 font-medium"><%= comment.text %></p>
      <p class="text-gray-500 font-medium">by <%= comment.author.name %></p>
      <hr class="my-4">
    <% if can? :destroy, comment %>
      <%= link_to "Delete Comment", user_post_comment_path(@post.author, @post, comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "bg-gradient-to-tr from-[#FF0000] via-[#FF0005] to-white text-white py-2 px-4 rounded-lg hover:bg-blue-800 cursor-pointer" %>
    <% end %>
    </div>
  <% end %>
    </div>
<% end %>
<% if can? :destroy, @post %>
  <%= link_to "Delete post", user_post_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "bg-gradient-to-tr from-[#FF0000] via-[#FF0005] to-white text-white py-2 px-4 rounded-lg hover:bg-blue-800 cursor-pointer mr-4" %>
<% end %> 
<%= link_to "Create Comment", new_user_post_comment_path(@user, @post), class: "bg-gradient-to-tr from-[#3FBFED] via-[#35A5E5] to-[#319AE0] text-white py-2 px-4 rounded-lg hover:bg-blue-800 cursor-pointer" %>
</div>